package com.blog.blogbackend.entity;

public enum NotificationType {
    AUTHOR_APPLICATION_SUBMITTED,
    AUTHOR_APPLICATION_APPROVED,
    AUTHOR_APPLICATION_REJECTED,
    CATEGORY_REQUEST_SUBMITTED,
    CATEGORY_REQUEST_APPROVED,
    CATEGORY_REQUEST_REJECTED,
    COMMENT_ON_POST,
    COMMENT_REPLY
}
